[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --workers=1 --worker-class=gevent --max-requests=10 --max-requests-jitter=5"